## 利用GitHub Actions每天 ##

name: baiduPush

# 两种触发方式：一、push代码，二、每天国际标准时间23点（北京时间+8即早上7点）运行
#on:
#  push:
#  schedule:
#    - cron: '0 23 * * *'
on:
   schedule:
     - cron: '*/5 * * * *' # 每5分钟一次，测试用

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
        with:
          python-version: '3.8'
      - name: 'Run baiduPush' # 步骤二，执行sh命令文件
        run: 
          python test.py
        
        
